import {FFmpeg} from "https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@0.12.15/dist/esm/index.js";
import {fetchFile,toBlobURL} from "https://cdn.jsdelivr.net/npm/@ffmpeg/util@0.12.2/dist/esm/index.js";
import JSZip from "https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm";
const $=id=>document.getElementById(id),CORE="https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd",PRESETS=[["0",48],["1",64],["2",80],["3",96],["4",112],["5",128],["6",144],["7",160],["8",176],["9",192],["a",36],["b",48],["c",60],["d",72],["e",84],["f",96],["g",108]];
const s={files:[],ff:null,loaded:false,xw:null,xready:false,busy:false,cancel:false};
const clean=p=>String(p||"").replace(/\\/g,"/").replace(/^\/+/,"").split("/").filter(x=>x&&x!=="."&&x!=="..").join("/");
const fpath=f=>clean(f.webkitRelativePath||f.name);
const isAudio=f=>/\.(mp3|wav|flac|m4a|mp4|aac|ogg|oga|opus|webm|wma|aiff|aif|alac|mka|caf|ac3|eac3|amr|ape|m4b)$/i.test(f.name||"");
const ext=()=>{const t=$("extension").value.trim().replace(/^\./,"");if(t&&t.toLowerCase()!=="auto")return t;return({ogg:"ogg",opus:"opus",mp3:"mp3",m4a:"m4a",aac:"aac",webm:"webm",flac:"flac",wav:"wav","xhe-aac":"m4a"})[$("format").value]||"bin"};
const br=()=>{let n=Number($("bitrate").value);if(!Number.isFinite(n)||n<=0)n=128;return String($("bitrateUnit").value==="Mbps"?n*1000:n)+"k"};
const outName=(src,root)=>clean((root||"converted-audio")+"/"+fpath(src).replace(/\.[^.]+$/i,"")+"."+ext());
function log(x){const e=$("log");e.textContent+=(e.textContent?"\n":"")+x;e.scrollTop=e.scrollHeight}
function stat(x,c=""){
  const el=document.getElementById("engineStatus");
  if(!el){
    console.warn("Audio Batch Converter: #engineStatus is missing.");
    return;
  }
  el.textContent=x;
  el.className="status "+c;
}
function size(n){let u=["B","KB","MB","GB"],i=0,v=n;while(v>=1024&&i<3){v/=1024;i++}return v.toFixed(i?1:0)+" "+u[i]}
function refresh(){ $("fileCount").textContent=s.files.length;$("totalSize").textContent=size(s.files.reduce((a,f)=>a+f.size,0));$("outputBadge").textContent=ext();$("startBtn").disabled=!s.files.length||s.busy;$("fileList").textContent=s.files.length?s.files.map(fpath).join("\n"):"No files selected."}
function setFiles(fs){s.files=Array.from(fs||[]).filter(isAudio);$("log").textContent=`Loaded ${s.files.length} audio file(s).`;refresh()}
async function dropEntries(items){const out=[];async function walk(e,p){if(e.isFile){await new Promise(r=>e.file(f=>{if(isAudio(f)){try{Object.defineProperty(f,"webkitRelativePath",{value:clean(p+f.name),configurable:true})}catch{}out.push(f)}r()},r));}else if(e.isDirectory){const rd=e.createReader();let es=[];while(true){const b=await new Promise(r=>rd.readEntries(r));if(!b.length)break;es.push(...b)}for(const c of es)await walk(c,p+e.name+"/")}}for(const it of Array.from(items||[])){const e=it.webkitGetAsEntry?.();if(e)await walk(e,"")}return out}
async function loadFF(){
  if(s.loaded)return s.ff;
  stat("Loading FFmpeg…","warn");
  log("[Engine] Starting FFmpeg WebAssembly load.");
  if(typeof FFmpeg!=="function"){
    throw new Error("FFmpeg module is unavailable. Check that the page is being served over HTTP(S) and that the CDN module can be reached.");
  }
  const f=new FFmpeg();f.on("log",({message})=>message&&log("[FFmpeg] "+message));await f.load({coreURL:await toBlobURL(CORE+"/ffmpeg-core.js","text/javascript"),wasmURL:await toBlobURL(CORE+"/ffmpeg-core.wasm","application/wasm")});s.ff=f;s.loaded=true;stat("FFmpeg ready","good");return f}
function common(i){const a=["-i",i,"-map","0:a:0"],fs=[],v=Number($("volume").value);if(v)fs.push("volume="+Math.pow(10,v/20).toFixed(7));if($("normalize").checked)fs.push("loudnorm=I=-16:TP=-1.5:LRA=11");if(fs.length)a.push("-af",fs.join(","));if($("format").value!=="xhe-aac"&&$("sampleMode").value==="fixed")a.push("-ar",String(Math.max(1000,Math.min(384000,Math.round(Number($("sampleRate").value)||44100)))));if($("channels").value!=="keep")a.push("-ac",$("channels").value);if($("metadata").value==="drop")a.push("-map_metadata","-1");return a}
function ffArgs(i,o){const f=$("format").value,a=common(i),b=br(),m=$("rateMode").value,q=Number($("quality").value)||4;if(f==="ogg"){a.push("-c:a","libvorbis");m==="vbr"?a.push("-q:a",String(Math.max(-1,Math.min(10,q)))):a.push("-b:a",b)}else if(f==="opus"){a.push("-c:a","libopus","-b:a",b,"-vbr",m==="vbr"?"on":m==="cvbr"?"constrained":"off","-compression_level",String(Math.max(0,Math.min(10,Number($("opusComplexity").value)||10))),"-application",$("opusApplication").value);if($("opusFrame").value)a.push("-frame_duration",$("opusFrame").value)}else if(f==="mp3"){a.push("-c:a","libmp3lame");m==="vbr"?a.push("-q:a",String(Math.max(0,Math.min(9,Math.round(q))))):a.push("-b:a",b)}else if(f==="m4a"){a.push("-c:a","aac","-b:a",b);if($("faststart").checked)a.push("-movflags","+faststart")}else if(f==="aac")a.push("-c:a","aac","-b:a",b,"-f","adts");else if(f==="webm")a.push("-c:a","libopus","-b:a",b);else if(f==="flac")a.push("-c:a","flac","-compression_level",String(Math.max(0,Math.min(12,Number($("flacCompression").value)||5))));else if(f==="wav")a.push("-c:a","pcm_s16le");else throw new Error("Unsupported browser format");a.push("-y",o);return a}
function preset(){const p=$("xhePreset").value;if(p!=="auto")return p;let w=Number($("bitrate").value)||128,b=PRESETS[0];for(const x of PRESETS)if(Math.abs(x[1]-w)<Math.abs(b[1]-w))b=x;return b[0]}
async function xhe(){if(s.xready)return s.xw;if(location.protocol==="file:")throw new Error("Serve the page through VSCode web preview/Live Server or GitHub Pages; file:// cannot reliably load module workers.");const w=new Worker(new URL("./xhe-worker.js",import.meta.url),{type:"module"});s.xw=w;await new Promise((res,rej)=>{const t=setTimeout(()=>rej(new Error("xHE-AAC WebAssembly did not initialize. Run the included Emscripten/GitHub Actions build first.")),30000);w.onmessage=e=>{if(e.data.type==="ready"){clearTimeout(t);s.xready=true;$("xheStatus").textContent="xHE-AAC WebAssembly ready.";res()}else if(e.data.type==="error"){clearTimeout(t);rej(new Error(e.data.message))}};w.onerror=e=>{clearTimeout(t);rej(new Error(e.message||"xHE worker failed"))}});return w}
async function encodeXhe(wav,p){const w=await xhe(),id=Date.now()+Math.random();return await new Promise((res,rej)=>{const h=e=>{if(e.data.id!==id)return;w.removeEventListener("message",h);e.data.type==="result"?res(new Uint8Array(e.data.bytes)):rej(new Error(e.data.message||"xHE encoding failed"))};w.addEventListener("message",h);w.postMessage({type:"encode",id,preset:p,seamless:$("xheExpert").value==="seamless",frameInterval:Number($("xheFrame").value)||42,bytes:wav},[wav.buffer])})}
async function one(f,i){const ff=await loadFF(),inp=`/work/in_${i}`,out=`/work/out_${i}.${ext()}`;await ff.writeFile(inp,await fetchFile(f));if($("format").value==="xhe-aac"){const wav=`/work/xhe_${i}.wav`,rate=$("sampleMode").value==="fixed"?Math.max(32000,Math.min(48000,Math.round(Number($("sampleRate").value)||44100))):44100,ch=$("channels").value==="keep"?2:Number($("channels").value),a=["-i",inp,"-map","0:a:0","-ar",String(rate),"-ac",String(ch)],fs=[],v=Number($("volume").value);if(v)fs.push("volume="+Math.pow(10,v/20).toFixed(7));if($("normalize").checked)fs.push("loudnorm=I=-16:TP=-1.5:LRA=11");if(fs.length)a.push("-af",fs.join(","));a.push("-c:a","pcm_s16le","-y",wav);await ff.exec(a);const wb=await ff.readFile(wav),p=preset(),r=await encodeXhe(wb,p);try{await ff.deleteFile(wav);await ff.deleteFile(inp)}catch{}return r}else{await ff.exec(ffArgs(inp,out));const r=await ff.readFile(out);try{await ff.deleteFile(inp);await ff.deleteFile(out)}catch{}return r}}
async function batch(){if(!s.files.length||s.busy)return;s.busy=true;s.cancel=false;$("startBtn").disabled=true;$("cancelBtn").disabled=false;$("bar").style.width="0%";$("log").textContent="";try{const zip=new JSZip(),root=clean($("prefix").value.trim()||"converted-audio");let ok=0,fail=0;for(let i=0;i<s.files.length;i++){if(s.cancel)break;$("current").textContent=`${i+1} / ${s.files.length}: ${fpath(s.files[i])}`;$("bar").style.width=(i/s.files.length*100).toFixed(1)+"%";try{const d=await one(s.files[i],i);const op=outName(s.files[i],root);zip.file(op,d);ok++;log(`✓ ${fpath(s.files[i])} → ${op}`)}catch(e){fail++;log(`✗ ${fpath(s.files[i])} :: ${e?.message||e}`)}}if(s.cancel){stat("Cancelled","bad");return}if(!ok)throw new Error("No files converted successfully.");const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=root+".zip";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);$("bar").style.width="100%";stat(`Complete: ${ok} converted`,`good`);$("current").textContent=`Finished. ${fail} failed.`}catch(e){console.error("Audio Batch Converter error:",e);stat("Error","bad");log("ERROR: "+(e?.message||e));$("current").textContent="Conversion stopped."}finally{s.busy=false;$("cancelBtn").disabled=true;$("startBtn").disabled=!s.files.length}}
$("folderBtn").onclick=e=>{e.stopPropagation();$("folderInput").click()};$("filesBtn").onclick=e=>{e.stopPropagation();$("filesInput").click()};$("folderInput").onchange=e=>setFiles(e.target.files);$("filesInput").onchange=e=>setFiles(e.target.files);$("drop").onclick=e=>{if(!e.target.closest("button"))$("folderInput").click()};for(const n of ["dragenter","dragover"])$("drop").addEventListener(n,e=>{e.preventDefault();$("drop").classList.add("drag")});for(const n of ["dragleave","drop"])$("drop").addEventListener(n,e=>{e.preventDefault();$("drop").classList.remove("drag")});$("drop").addEventListener("drop",async e=>{const it=e.dataTransfer?.items;if(it&&Array.from(it).some(x=>x.webkitGetAsEntry?.()))setFiles(await dropEntries(it));else setFiles(e.dataTransfer?.files||[])});$("format").onchange=()=>{$("xheCard").classList.toggle("hidden",$("format").value!=="xhe-aac");refresh()};$("extension").oninput=refresh;$("startBtn").onclick=batch;$("cancelBtn").onclick=()=>s.cancel=true;$("clearBtn").onclick=()=>{s.files=[];$("folderInput").value="";$("filesInput").value="";$("log").textContent="Ready.";$("bar").style.width="0";refresh()};refresh();
